# ======= SAFE TO CHANGE =======
HOST = "localhost"
PORT = 45678
TEST_DISPLAY_LENGTH = 5
REFRESH_TICKRATE = 30 # Must be much higher than server_tickrate
SERVER_TICKRATE = 10

# ======= MUST BE IDENTICAL TO SERVER =======
MAX_THRUST = 0.01
TURNIT = 0.03
THRUSTIT = 0.002
OBJ_RADIUS = 0.05
WIN_CAP = 3



# ======= NOT SAFE TO CHANGE =======
WINDOW_WIDTH = 900
WINDOW_HEIGHT = 900

