# ======= SAFE TO CHANGE =======
HOST = "localhost"
PORT = 45678
TEST_DISPLAY_LENGTH = 0
REFRESH_TICKRATE = 60 # Must be much higher than server_tickrate
SERVER_TICKRATE = 17

# ======= MUST BE IDENTICAL TO SERVER =======
MAX_THRUST = 0.01
TURNIT = 0.06
THRUSTIT = 0.002
OBJ_RADIUS = 0.05
SHOOT_RADIUS = 0.01
SHOOT_SPEED = 0.01
WIN_CAP = 3
VE_RADIUS = 0.04
OB_RADIUS = 0.08



# ======= NOT SAFE TO CHANGE =======
WINDOW_WIDTH = 900
WINDOW_HEIGHT = 900

